version: "3.8"

services:
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4202
      - POSTGRES_DB=CRUD
